### ISSUE TITLE
Problem Running

### ISSUE THREAD

**Issue by rdevivo155** [markydoodled/Journal.it#1]
Hi.. I want to help you with UITest but I can't run the app 

<img width="452" alt="image" src="https://user-images.githubusercontent.com/79980819/206525848-f6030381-c4b8-4fb1-a769-99455cbf508f.png">

**Comment by markydoodled** [comment]
Hi, 
These errors happen because the package dependencies haven't been cloned with the project.
The best way to get these back is to: 
- Click on the project file in the Xcode Editor
- Under "Project" click "Journal.it" then "Package Dependencies"
- Click the add button
- Search for the package listed in the error 
- Select it and click the add package button
- Repeat this for each of the missing packages
